### PR TITLE
Purge all MultiMC references and sundry

### PR DESCRIPTION
**Pull request by txtsd**
This PR purges MultiMC references from all environment variables, python functions and python variables, including comments.

I have not touched the references to the ssh keys in `config/readme.txt` because we don't use them. Let me know if we'd like them removed instead.

Also, in `generateForge.py`, I've changed `files.multimc.org` to `meta.polymc.org`, even if those lines were commented out. If that's unwanted, let me know and I'll revert it.

Additionally, the `multimc` cloned folder is now `polymc`. So running `./clone.sh` again will be required, and the old `multimc` folder will have to be removed or it will show in untracked files.

Finally, the `config/config_local.sh.example` has its example data randomized as it previously contained unwanted personal information.

### CODE REVIEW

**Comment by ghost** [comment]
Change all "polymc" directory references to use the PMC_dir envvar and then I can do a full review sometime later

**Comment by txtsd** [comment]
> Change all "polymc" directory references to use the PMC_dir envvar and then I can do a full review sometime later

Will do!

Do you also want me to add a `requirements.txt` while I'm at it?

**Comment by ghost** [comment]
Yes please do

**Comment by txtsd** [comment]
Okay both `PMC_DIR` and `UPSTREAM_DIR` are accessed via the environment variables in the python files now.

Added a `requirements.txt` and also a `README.md` for the repo.

Made the .py files launch explicitly via `python` instead of bash hashbangs. This will help if later we decide to use `pipenv` instead of just requirements.txt. I maintain a `Pipfile` for my local virtualenv so let me know if it's needed.

Also sorted the imports and removed 2 occurrences of a python2 era import.

**Pull request merged**
