### PR TITLE
Python and shellscript changes

### PR DESCRIPTION
**Pull request by txtsd**
Commit messages are self-explanatory~

### CODE REVIEW

**Comment by txtsd** [comment]
Oops I meant to PR to develop

**Comment by txtsd** [comment]
Actually, it won't let me make a PR to develop.

**Comment by txtsd** [comment]
https://github.com/PolyMC/meta/blob/f8dd68b649193692edfdfd79778d563878e21866/generateForge.py#L81
https://github.com/PolyMC/meta/blob/f8dd68b649193692edfdfd79778d563878e21866/generateForge.py#L130

These two are dead code, should I remove them?

**Comment by Scrumplex** [comment]
> Oops I meant to PR to develop

There is no develop anymore

**Review by Scrumplex — APPROVED** [review]

**Pull request merged**
