### PR TITLE
remove dirty ugly hack that makes lwjgl3 not able to be changed

### PR DESCRIPTION
**Pull request by d-513**
doesnt *seem* to cause side effects

### CODE REVIEW

**Comment by Scrumplex** [comment]
Probably fine. But I would really like to know why it was there in the first place tbh

**Comment by d-513** [comment]
same, it seems to just be an obstacle. without hack you can change lwjgl  version, so fix some issues pepole have with HiDPI for example. Also will be able to do m1 soon probably , but the draft pr made me explode

**Review by Scrumplex — APPROVED** [review]
let's just YOLO

**Comment by d-513** [comment]
gaming

**Comment by kthchew** [comment]
Thanks! By the way, from Git history, it seems like the original reason this was added was to ensure that a compatible version of LWJGL was used. For example, lets say you have an instance with MC 1.13-pre1 (uses LWJGL 3.1.2). You then update the MC version to 1.13 (requires at least LWJGL 3.1.6). The LWJGL version will not automatically update, and thus the instance will crash on startup unless the user also knows to update the LWJGL version.

Seems like a more "correct" solution would be to ensure that the version is greater than or equal to the recommended LWJGL version, though I don't know if that's easy to do. (Or, the LWJGL version could just reset when a new MC version is selected.)

**Comment by d-513** [comment]
> Thanks! By the way, from Git history, it seems like the original reason this was added was to ensure that a compatible version of LWJGL was used. For example, lets say you have an instance with MC 1.13-pre1 (uses LWJGL 3.1.2). You then update the MC version to 1.13 (requires at least LWJGL 3.1.6). The LWJGL version will not automatically update, and thus the instance will crash on startup unless the user also knows to update the LWJGL version.
> 
> Seems like a more "correct" solution would be to ensure that the version is greater than or equal to the recommended LWJGL version, though I don't know if that's easy to do. (Or, the LWJGL version could just reset when a new MC version is selected.)

right now we can keep it imo, and if mojang bumps we can figure out a better way. We discussed the origins of this in the discord and found the original issue with some pre release. But yeah, compare would be nice, or at least detect bumped suggested version and maybe inform user

**Pull request merged**
